"""Initial models1

Revision ID: 46c91fbbda79
Revises: ebce9bc895f3
Create Date: 2025-04-01 20:47:28.693306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c91fbbda79'
down_revision: Union[str, None] = 'ebce9bc895f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sobrenome', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('rg_ie', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('Admin', sa.CHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pessoas_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pessoas_id'))

    op.drop_table('pessoas')
    # ### end Alembic commands ###
