"""Add new columns

Revision ID: 76b1306013a2
Revises: 3094deb7d2bd
Create Date: 2025-04-08 19:22:13.045644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '76b1306013a2'
down_revision: Union[str, None] = '3094deb7d2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('senha', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('Admin')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Admin', mysql.CHAR(length=1), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('role')
        batch_op.drop_column('senha')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
