"""add legado field to pessoa

Revision ID: f3a7deb7b4e4
Revises: 46c91fbbda79
Create Date: 2025-04-02 13:57:46.889497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3a7deb7b4e4'
down_revision: Union[str, None] = '46c91fbbda79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_column('Admin')
        batch_op.add_column(sa.Column('admin', sa.CHAR(), nullable=True))
        batch_op.add_column(sa.Column('legado', sa.CHAR(), nullable=True))
        

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_column('admin')
        batch_op.add_column(sa.Column('Admin', mysql.CHAR(length=1), nullable=True))
        batch_op.drop_column('legado')
        

    # ### end Alembic commands ###
